export const browserCoreExamples = [
  "agdi browser status",
  "agdi browser start",
  "agdi browser stop",
  "agdi browser tabs",
  "agdi browser open https://example.com",
  "agdi browser focus abcd1234",
  "agdi browser close abcd1234",
  "agdi browser screenshot",
  "agdi browser screenshot --full-page",
  "agdi browser screenshot --ref 12",
  "agdi browser snapshot",
  "agdi browser snapshot --format aria --limit 200",
  "agdi browser snapshot --efficient",
  "agdi browser snapshot --labels",
];

export const browserActionExamples = [
  "agdi browser navigate https://example.com",
  "agdi browser resize 1280 720",
  "agdi browser click 12 --double",
  'agdi browser type 23 "hello" --submit',
  "agdi browser press Enter",
  "agdi browser hover 44",
  "agdi browser drag 10 11",
  "agdi browser select 9 OptionA OptionB",
  "agdi browser upload /tmp/agdi/uploads/file.pdf",
  'agdi browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "agdi browser dialog --accept",
  'agdi browser wait --text "Done"',
  "agdi browser evaluate --fn '(el) => el.textContent' --ref 7",
  "agdi browser console --level error",
  "agdi browser pdf",
];
